site_name: Git
google_analytics: ['UA-68978617-1', 'magizbox.com']
pages:
- "Home": "index.md"
- "Installation": "install.md"
- "Doc":
  - "Commit": "commit.md"
  - "Branch": "branch.md"
  - "Tag": "tag.md"
  - "Submodule": "submodule.md"
  - "Config": "config.md"
  - "Github": "github.md"
  - "Workflow": "team_workflow.md"
markdown_extensions:
    - footnotes
extra_css:
  - css/book.css
  - css/course.css
  - css/video.css
extra_javascript:
  - js/underscore.js
  - js/gspreadsheet.js
  - js/book.js
  - js/course.js
  - js/video.js
